# Generated by Django 3.2.4 on 2021-07-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210711_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuprequest',
            name='extra_note',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
